# Numpy Tutorials

In [ ]:
#Numpy is very similer to list. Numpy requires less memory, fast and convinient in compare to lists. Examples

In [3]:
import numpy as np
import time
import sys

l=range(1000)
print(sys.getsizeof(5)*len(l))  #28000 bytes
array=np.arange(1000)
print(array.size*array.itemsize) #4000 bytes

28000
4000


In [13]:
a=np.array([5,6,8]) # We can create numpy array like list and process same as list. It is one dimension array
a[0]

a1=np.array([[1,2],[3,4]]) # dimentional array
a1.ndim # print dimension
a1.itemsize # Will give byte size of each element
a1.dtype

a2=np.array([[1,2],[3,4]], dtype=np.float64)
a2.itemsize # Itemsize of float is 8 byte per element
a2
a2.size #Size of array
a2.shape # Two rows and two columns

(2, 2)

In [20]:
import numpy as np
np.zeros((3,2))
np.ones((4,5)) # To show zeros and ones in numpy

l=range(5) # It will create list of length 5
a=np.arange(1,5) # Behaves like list range function
a1=np.arange(1,8,2) #2 is step size
a2=np.linspace(1,5,10) #10 is numbers to be generated
a.reshape(2,3) # to reshape your matrix
a.ravel() # Make it one dimention or flatten that array. These function will not alter the orignal array

#a.min(),a.max(),a.sum() or a.sum(axis=1), np.sqrt(a), a+b, a*b,a-b, adot(b) - will give matrix product


(4,)

# Slicing and Dicing

In [26]:
import numpy as np
n=[6,7,8]
n[0:2] # It will not cover2 
n[-1]

a=np.array([6,7,8])
a[0:2]
a[-1]

a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a
a[0,2]
a[0:2,2] #0:2 will give rows and last 2 traverse column
a[-1] # Last row
a[-1,0:2] # Last two columns of last two rows
a[:,1,3]  # All rows and last two columns

for row in a:
    print(row)   # print the mitrix
    
for cell in a.flat:
    print(cell)

IndexError: too many indices for array

In [40]:
import numpy as np
b=np.arange(6).reshape(3,2)
b

c=np.arange(6,12).reshape(3,2) # arange will give 6 to 12 numbers
c

np.vstack((b,c)) # Stacking the two matrixes or place one box on other on top of it.
np.hstack((b,c))

g=np.arange(30).reshape(2,15)
g
np.hsplit(g,3) # Divide or split into 3 equalt array

result= np.hsplit(g,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [46]:
import numpy as np
Sample=np.arange(12).reshape(3,4)
b= a>4
b
a[b] #Fetch all the element which is greater than 4
a[b] =1 #We are set the 1 value whose is greater than 4
a

array([[1, 1, 1],
       [1, 2, 3],
       [1, 3, 2]])

In [53]:
import numpy as pd
a = np.arange(12).reshape(3,4)
for row in a:
    for cell in row:
        print(cell)    # It will flaten the elements or print every element. or u can do in thsi way also
        
for cell in a.flatten():
    print(cell)
    
for rows in np.nditer(a,order='C'): # c for c or row wise traversing or f for coulumn wise traversing and itteration is for element wise 
    print(row)

b=np.arange(3,15,4).reshape(3,1)
b

for x,y in np.nditer([a,b]): # Iteration of both the array simultanously. Shapes should be same for both the array
    print(x,y)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
