# Numpy Tutorials

In [ ]:
#Numpy is very similer to list. Numpy requires less memory, fast and convinient in compare to lists. Examples

In [3]:
import numpy as np
import time
import sys

l=range(1000)
print(sys.getsizeof(5)*len(l))  #28000 bytes
array=np.arange(1000)
print(array.size*array.itemsize) #4000 bytes

28000
4000


In [13]:
a=np.array([5,6,8]) # We can create numpy array like list and process same as list. It is one dimension array
a[0]

a1=np.array([[1,2],[3,4]]) # dimentional array
a1.ndim # print dimension
a1.itemsize # Will give byte size of each element
a1.dtype

a2=np.array([[1,2],[3,4]], dtype=np.float64)
a2.itemsize # Itemsize of float is 8 byte per element
a2
a2.size #Size of array
a2.shape # Two rows and two columns

(2, 2)

In [20]:
import numpy as np
np.zeros((3,2))
np.ones((4,5)) # To show zeros and ones in numpy

l=range(5) # It will create list of length 5
a=np.arange(1,5) # Behaves like list range function
a1=np.arange(1,8,2) #2 is step size
a2=np.linspace(1,5,10) #10 is numbers to be generated
a.reshape(2,3) # to reshape your matrix
a.ravel() # Make it one dimention or flatten that array. These function will not alter the orignal array

#a.min(),a.max(),a.sum() or a.sum(axis=1), np.sqrt(a), a+b, a*b,a-b, adot(b) - will give matrix product


(4,)

# Slicing and Dicing

In [26]:
import numpy as np
n=[6,7,8]
n[0:2] # It will not cover2 
n[-1]

a=np.array([6,7,8])
a[0:2]
a[-1]

a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a
a[0,2]
a[0:2,2] #0:2 will give rows and last 2 traverse column
a[-1] # Last row
a[-1,0:2] # Last two columns of last two rows
a[:,1,3]  # All rows and last two columns

for row in a:
    print(row)   # print the mitrix
    
for cell in a.flat:
    print(cell)

IndexError: too many indices for array

In [40]:
import numpy as np
b=np.arange(6).reshape(3,2)
b

c=np.arange(6,12).reshape(3,2) # arange will give 6 to 12 numbers
c

np.vstack((b,c)) # Stacking the two matrixes or place one box on other on top of it.
np.hstack((b,c))

g=np.arange(30).reshape(2,15)
g
np.hsplit(g,3) # Divide or split into 3 equalt array

result= np.hsplit(g,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [46]:
import numpy as np
Sample=np.arange(12).reshape(3,4)
b= a>4
b
a[b] #Fetch all the element which is greater than 4
a[b] =1 #We are set the 1 value whose is greater than 4
a

array([[1, 1, 1],
       [1, 2, 3],
       [1, 3, 2]])

In [53]:
import numpy as pd
a = np.arange(12).reshape(3,4)
for row in a:
    for cell in row:
        print(cell)    # It will flaten the elements or print every element. or u can do in thsi way also
        
for cell in a.flatten():
    print(cell)
    
for rows in np.nditer(a,order='C'): # c for c or row wise traversing or f for coulumn wise traversing and itteration is for element wise 
    print(row)

b=np.arange(3,15,4).reshape(3,1)
b

for x,y in np.nditer([a,b]): # Iteration of both the array simultanously. Shapes should be same for both the array
    print(x,y)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
[ 8  9 10 11]
0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [ ]:
# The NumPy library is a popular Python library used for scientific computing applications, and is an acronym for 
# "Numerical Python". NumPy's operations are divided into three main categories: Fourier Transform and Shape Manipulation, 
# Mathematical and Logical Operations, and Linear Algebra and Random Number Generation. To make it as fast as possible, 
# NumPy is written in C and Python.

In [ ]:
# Here, in order to add 2 to each element in the list x, we have to traverse the entire list and add 2 to each element 
# individually. it can be one dimentional and two dimentional both.

x = [2, 3, 4, 5, 6]
y = [a + 2 for a in x]

import numpy as np
nums = np.array([2, 3, 4, 5, 6])
nums2 = nums + 2

In [8]:
# import numpy as np
# print(np.array([2, 3, 4, 5, 6])+2)

TypeError: can only concatenate list (not "str") to list

In [ ]:
#some basic functions in numpy.

nums = np.arange(2, 7, 2) # start,1-end,step size.

zeros = np.zeros((5, 4)) # Two dimentional Matrix or array wirh values zeros.
ones = np.ones(5) # one dimentional array with values one.
lin = np.linspace(1, 10, 10) # It will equally divided the values into 10 parts. start,end, and equall partition.
idn = np.eye(4) #An identity matrix is a matrix with zeros across rows and columns except the diagonal.

random = np.random.rand(2, 3) #The matrix contains uniform distribution of numbers between 0 and 1:
random = np.random.randn(2, 3) # to create a matrix of random numbers with the normal" distribution use the randn method
random = np.random.randint(50,100,5) # start, end , number of integer you want.

nums2 = nums.reshape(4, 4) # reshaping or changing the array from one dim to another dim.


In [ ]:
# Functions in Numpy

np.log()
np.exp()
np.sqrt()
np.sin()
np.dot() # for dot product
np.max()
np.min()
np.argmin()
np.argmax()
np.linalg.inv(Y) # inverse of every element.
np.linalg.det(X) # determinent of matrix
np.trace(X) # The trace of a matrix is the sum of all the elements in the diagonal of a matrix

# Some important functions 

In [ ]:
# Lambda,map,filter and reduse function is maing object data structure so need to convert it.
#Lambda function - A lambda operator or lambda function is used for creating small, one-time, anonymous function in Python.

#lambda arguments : expression

add = lambda x, y : x + y 
double = lambda x: 2*x
print (add(2, 3)) # Output: 5

# Map funcion -
#map(function_object, iterable1, iterable2,...)
map(multiply2, [1, 2, 3, 4])
list_a = [1, 2, 3]
list_b = [10, 20, 30]
  
map(lambda x, y: x + y, list_a, list_b) # Output: [11, 22, 33]

# Filter function - Filtering the items from list or any datatype.

#filter(function_object, iterable)

a = [1, 2, 3, 4, 5, 6]
filter(lambda x : x % 2 == 0, a) # Output: [2, 4, 6]

#Reduse - It also return object type datastructure and works on f(f(m,n),p)

n=[4,3,2,1]
print(reduce(lambda x,y:x*y,n)) # ((4*3)*2)*1 

#Zip function -
#zip takes n number of iterables and returns list of tuples. it makes object type structure.


list_a = [1, 2, 3, 4, 5]
list_b = ['a', 'b', 'c', 'd', 'e']

zipped_list = zip(list_a, list_b) # [(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]
#zip can truncates the extra elements of list_b in the output.

list_a = [1, 2, 3]
list_b = ['a', 'b', 'c', 'd', 'e']

zipped_list = zip(list_a, list_b)

print (zipped_list) # [(1, 'a'), (2, 'b'), (3, 'c')]

#Unzip a list of tuples
zipper_list = [(1, 'a'), (2, 'b'), (3, 'c')]
 
list_a, list_b = zip(*zipper_list)
print (list_a) # (1, 2, 3)
print (list_b) # ('a', 'b', 'c')



In [1]:
# Map can applied to Series in this way.
import pandas as pd
lis=[1, 2, 3, 4]
ser=pd.Series(lis)
ser.map(lambda x : x*2) #Output [2, 4, 6, 8]

0    2
1    4
2    6
3    8
dtype: int64

In [ ]:
#Enumerate() method adds a counter to an iterable and returns it in a form of enumerate object
#enumerate(iterable, start=0)

l1 = ["eat","sleep","repeat"] 
s1 = "geek"

print ("Return type:",type(obj1)) 
print (list(enumerate(l1)))

cities=[jaipur,bangalore,mumbai,pune,noida]
for i,city in enumerate(cities)

In [9]:
cities=['jaipur','bangalore','mumbai','pune','noida']
for i,cities in enumerate(cities):
    print(i,cities)

0 jaipur
1 bangalore
2 mumbai
3 pune
4 noida
